title: Webwide Magazine
metadata:
    description: 'Discover quality content for web designers and developers. Tutorials, resources, industry news, case-studies, thought-pieces and more brought to you by the wonderful Webwide community completely free.'

