home:
  alias: '/blog'

pages:
  theme: webwide
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: false
  js_pipeline: false
  js_minify: false

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true

errors:
  display: 1
  log: true
